---
- hosts: znc

  tasks: 
    
  # Optional: If restoring from a local backup of the config
  #- name: Copy docker-znc data directory
    # Update src to the actual path of the default znc configuration
  #  synchronize: src=docker-znc/znc-default/ dest=~/.znc recursive=yes

  - name: Install pip
    apt: name="python-pip" state=present
    when: ansible_pkg_mgr == 'apt'

  - name: Install pip
    yum: name="python-pip" state=present
    when: ansible_pkg_mgr == 'yum'

  - name: Install docker
    apt: name="docker.io" state=present
    when: ansible_pkg_mgr == 'apt'

  - name: Install docker
    yum: name="docker" state=present
    when: ansible_pkg_mgr == 'yum'

  - name: Create znc user
    user: name=znc groups=users,docker append=yes

  - name: Copy systemd service file
    synchronize: src=znc.service dest=/etc/systemd/user/

  - name: Enable docker container at boot through systemd
    command: systemctl --user enable znc.service 

