---
- hosts: znc

  tasks: 
  - name: Copy docker-znc data directory
    # Update src to the actual path of the default znc configuration
    synchronize: src=docker-znc/znc-default/ dest=~/.znc recursive=yes

  - name: Install pip
    apt: name="python-pip" state=present

  - name: Install docker
    apt: name="docker.io" state=present

  - name: Install Docker-py
    pip: name=docker-py state=present

  - name: Run docker container
    docker: image="chimeracoder/docker-znc-ssl" ports="6697:6697" volumes="~/.znc:/znc-data"
