---
- hosts: znc

  tasks: 
    
  # Optional: If restoring from a local backup of the config
  # Update src to the actual path of the default znc configuration
  #- name: Copy docker-znc data directory
  #  synchronize: src=docker-znc/znc-default/ dest=~/.znc recursive=yes

  - name: Install pip
    apt: name="python-pip" state=present
    when: ansible_pkg_mgr == 'apt'

  - name: Install pip
    yum: name="python-pip" state=present
    when: ansible_pkg_mgr == 'yum'

  - name: Add Docker PGP key
    command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    when: ansible_pkg_mgr == 'apt'

  - name: Install apt-transport-https
    apt: name="apt-transport-https" state=present
    when: ansible_pkg_mgr == 'apt'

  - name: Add jessie-backports repository
    apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present update_cache=yes
    when: ansible_pkg_mgr == 'apt'

  - name: Install docker
    apt: name="lxc-docker" state=present default_release="docker"
    when: ansible_pkg_mgr == 'apt'

  - name: Install docker
    yum: name="docker" state=present
    when: ansible_pkg_mgr == 'yum'

  - name: Create docker group
    group: name=docker state=present

  - name: Create znc user
    user: name=znc groups=users,docker append=yes

  - name: Create .znc config directory if it doesn't exist and ensure permissions
    file: path=~/.znc owner=znc group=users mode=0777 state=directory recurse=yes

  - name: Copy systemd service file
    synchronize: src=znc.service dest=/etc/systemd/system/znc.service

  - name: Reload daemon in case the service file changed
    command: systemctl daemon-reload

  - name: Start znc service
    command: systemctl start znc.service 

  - name: Enable docker container at boot through systemd
    command: systemctl enable znc.service 
    

